#Code Book

### Variable Descriptions


|Variable  | Description
-----------|---------------
|activity	|	id activity 
|subject	|	Id the subject
|timeAcceleration_mean_X	|	mean acceleration signal x axis  
|timeAcceleration_mean_Y	|	mean acceleration signal y axis  
|timeAcceleration_mean_Z	|	mean acceleration signal z axis  
|timeAcceleration_std_X	|	standard deviation acceleration signal x axis  
|timeAcceleration_std_Y	|	standard deviation acceleration signal y axis  
|timeAcceleration_std_Z	|	standard deviation acceleration signal x axis  
|timeGravityAcceleration_mean_X	|	mean gravity acceleration signal x axis  
|timeGravityAcceleration_mean_Y	|	mean gravity acceleration signal y axis  
|timeGravityAcceleration_mean_Z	|	mean gravity acceleration signal z axis  
|timeGravityAcceleration_std_X	|	standard deviation gravity acceleration signal x axis  
|timeGravityAcceleration_std_Y	|	standard deviation gravity acceleration signal y axis  
|timeGravityAcceleration_std_Z	|	standard deviation gravity acceleration signal x axis  
|timeAccelerationJerk_mean_X	|	mean acceleration Jerk signal x axis  
|timeAccelerationJerk_mean_Y	|	mean acceleration Jerk signal y axis  
|timeAccelerationJerk_mean_Z	|	mean acceleration Jerk signal z axis  
|timeAccelerationJerk_std_X	|	standard deviation acceleration Jerk signal x axis  
|timeAccelerationJerk_std_Y	|	standard deviation acceleration Jerk signal y axis  
|timeAccelerationJerk_std_Z	|	standard deviation acceleration Jerk signal x axis  
|timeGyroscope_mean_X	|	mean gyroscope signal x axis  
|timeGyroscope_mean_Y	|	mean gyroscope signal y axis  
|timeGyroscope_mean_Z	|	mean gyroscope signal z axis  
|timeGyroscope_std_X	|	standard deviation gyroscope signal x axis  
|timeGyroscope_std_Y	|	standard deviation gyroscope signal y axis  
|timeGyroscope_std_Z	|	standard deviation gyroscope signal x axis  
|timeGyroscopeJerk_mean_X	|	mean gyroscope  Jerksignal x axis  
|timeGyroscopeJerk_mean_Y	|	mean gyroscope  Jerksignal y axis  
|timeGyroscopeJerk_mean_Z	|	mean gyroscope  Jerksignal z axis  
|timeGyroscopeJerk_std_X	|	standard deviation gyroscope Jerk signal x axis  
|timeGyroscopeJerk_std_Y	|	standard deviation gyroscope Jerk signal y axis  
|timeGyroscopeJerk_std_Z	|	standard deviation gyroscope Jerk signal x axis  
|timeAccelerationMagnitude_mean	|	mean acceleration magnitude signal x axis  
|timeAccelerationMagnitude_std	|	standard deviation acceleration magnitude signal x axis  
|timeGravityAccelerationMagnitude_mean	|	mean gravity acceleration magnitude signal x axis  
|timeGravityAccelerationMagnitude_std	|	standard deviation gravity acceleration magnitude signal x axis  
|timeAccelerationJerkMagnitude_mean	|	mean  acceleration Jerk magnitude signal x axis  
|timeAccelerationJerkMagnitude_std	|	standard  deviation acceleration  Jerk magnitude signal x axis  
|timeGyroscopeMagnitude_mean	|	mean gyroscope magnitude signal x axis  
|timeGyroscopeMagnitude_std	|	standard  deviation gyroscope magnitude signal x axis  
|timeGyroscopeJerkMagnitude_mean	|	mean Gyroscope Jerk Magnitude signal x axis  
|timeGyroscopeJerkMagnitude_std	|	standard  Gyroscope Jerk Magnitude signal x axis  
|frequencyAcceleration_mean_X	|	mean acceleration signal x axis  
|frequencyAcceleration_mean_Y	|	mean acceleration signal y axis  
|frequencyAcceleration_mean_Z	|	mean acceleration signal z axis  
|frequencyAcceleration_std_X	|	standard deviation acceleration signal x axis  
|frequencyAcceleration_std_Y	|	standard deviation acceleration signal y axis  
|frequencyAcceleration_std_Z	|	standard deviation acceleration signal x axis  
|frequencyAccelerationJerk_mean_X	|	mean acceleration Jerk signal x axis  
|frequencyAccelerationJerk_mean_Y	|	mean acceleration Jerk signal y axis  
|frequencyAccelerationJerk_mean_Z	|	mean acceleration Jerk signal z axis  
|frequencyAccelerationJerk_std_X	|	standard deviation acceleration Jerk signal x axis  
|frequencyAccelerationJerk_std_Y	|	standard deviation acceleration Jerk signal y axis  
|frequencyAccelerationJerk_std_Z	|	standard deviation acceleration Jerk signal x axis  
|frequencyGyroscope_mean_X	|	mean gyroscope signal x axis  
|frequencyGyroscope_mean_Y	|	mean gyroscope signal y axis  
|frequencyGyroscope_mean_Z	|	mean gyroscope signal z axis  
|frequencyGyroscope_std_X	|	standard deviation gyroscope signal x axis  
|frequencyGyroscope_std_Y	|	standard deviation gyroscope signal y axis  
|frequencyGyroscope_std_Z	|	standard deviation gyroscope signal z axis  
|frequencyAccelerationMagnitude_mean	|	mean acceleration magnitude
|frequencyAccelerationMagnitude_std	|	standard deviation acceleration magnitude 
|frequencyAccelerationJerkMagnitude_mean	|	mean  acceleration Jerk magnitude
|frequencyAccelerationJerkMagnitude_std	|	standard  deviation acceleration  Jerk magnitude 
|frequencyGyroscopeMagnitude_mean	|	mean Gyroscope magnitude magnitude
|frequencyGyroscopeMagnitude_std	|	standard  deviation  Gyroscope magnitude
|frequencyGyroscopeJerkMagnitude_mean	|	mean Gyroscope Jerk magnitude magnitude
|frequencyGyroscopeJerkMagnitude_std	|	standard  deviation  Gyroscope Jerk magnitude
|activityNames	|	Activity Names
